`timescale 1 ns / 1 ps

module tb_CNN_Core;

    parameter MEM_AWIDTH      = 16;
    parameter AXI_WORD_ADDR_WIDTH = 17;  // linear 16-bit word address space for FC3 weights
    parameter AXI_ADDR_WIDTH  = AXI_WORD_ADDR_WIDTH + 3;
    parameter AXI_DATA_DWIDTH = 16;
    parameter DWIDTH          = 16;
    parameter NBANKS          = 5;
    parameter TOTAL_DWIDTH    = NBANKS * DWIDTH;

    localparam [2:0] W_LOAD_CTRL = 3'd0;
    localparam [2:0] W_START     = 3'd1;
    localparam [2:0] W_DONE_CLR  = 3'd2;
    localparam [2:0] W_PING_FM   = 3'd3;
    localparam [2:0] W_PONG_FM   = 3'd4;
    localparam [2:0] W_WEIGHT    = 3'd5;
    localparam [2:0] W_BIAS      = 3'd6;

    localparam [2:0] R_STATUS    = 3'd0;

    // TB input generated by explicit_debug_dump_layers_q16.py.
    // Network shape: conv1 8x1x5x5, conv2 20x8x5x5, fc1 128x320, fc2 84x128, fc3 10x84.
    parameter [8*384-1:0] INPUT_Q16_FILE = "fixed_q16_params/input_q16.txt";

    localparam integer CONV1_W_BASE = 0;
    localparam integer CONV2_W_BASE = 200;
    localparam integer FC1_W_BASE   = 4200;
    localparam integer FC2_W_BASE   = 55400;
    localparam integer FC3_W_BASE   = 68840;

    localparam integer CONV1_B_BASE = 0;
    localparam integer CONV2_B_BASE = 8;
    localparam integer FC1_B_BASE   = 28;
    localparam integer FC2_B_BASE   = 156;
    localparam integer FC3_B_BASE   = 240;

    reg CLK;
    reg RST;

    reg  [AXI_ADDR_WIDTH-1:0]  axi_waddr_i;
    reg  [AXI_DATA_DWIDTH-1:0] axi_wdata_i;
    reg                        axi_wvalid_i;

    reg  [AXI_ADDR_WIDTH-1:0]  axi_raddr_i;
    reg                        axi_arvalid_i;
    wire [AXI_DATA_DWIDTH-1:0] axi_rdata_o;

    wire                       predict_valid_o;
    wire [3:0]                 predict_value_o;
    wire [2:0]                 state_o;
    wire                       done_o;

    integer i;
    integer fd;
    integer code;
    integer val;
    integer addr;

    reg [8*256-1:0] line_r;

    cnn_core #(
        .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH),
        .AXI_DATA_DWIDTH(AXI_DATA_DWIDTH),
        .AWIDTH(MEM_AWIDTH),
        .DWIDTH(DWIDTH),
        .NBANKS(NBANKS)
    ) dut (
        .CLK(CLK),
        .RST(RST),
        .axi_waddr_i(axi_waddr_i),
        .axi_wdata_i(axi_wdata_i),
        .axi_wvalid_i(axi_wvalid_i),
        .axi_raddr_i(axi_raddr_i),
        .axi_arvalid_i(axi_arvalid_i),
        .axi_rdata_o(axi_rdata_o),
        .predict_valid_o(predict_valid_o),
        .predict_value_o(predict_value_o),
        .state_o(state_o),
        .done_o(done_o)
    );

    initial begin
        CLK = 1'b0;
        forever #5 CLK = ~CLK;
    end

    task axi_write;
        input [2:0] sel_i;
        input [AXI_WORD_ADDR_WIDTH-1:0] addr_i;
        input [AXI_DATA_DWIDTH-1:0] data_i;
        begin
            @(negedge CLK);
            axi_waddr_i  = {sel_i, addr_i};
            axi_wdata_i  = data_i;
            axi_wvalid_i = 1'b1;

            @(posedge CLK);
            #1;

            @(negedge CLK);
            axi_wvalid_i = 1'b0;
            axi_waddr_i  = {AXI_ADDR_WIDTH{1'b0}};
            axi_wdata_i  = {AXI_DATA_DWIDTH{1'b0}};
        end
    endtask

    task axi_read;
        input [2:0] sel_i;
        input [AXI_WORD_ADDR_WIDTH-1:0] addr_i;
        begin
            @(negedge CLK);
            axi_raddr_i   = {sel_i, addr_i};
            axi_arvalid_i = 1'b1;

            @(posedge CLK);
            #1;

            @(negedge CLK);
            axi_arvalid_i = 1'b0;
        end
    endtask

    task load_bias_file;
        input [8*384-1:0] file_name_i;
        input integer base_addr_i;
        begin
            fd = $fopen(file_name_i, "r");

            if (fd == 0) begin
                $display("[WARN] cannot open %0s", file_name_i);
            end
            else begin
                addr = base_addr_i;

                while ($fgets(line_r, fd)) begin
                    code = $sscanf(line_r, "%h", val);

                    if (code == 1) begin
                        axi_write(W_BIAS, addr[AXI_WORD_ADDR_WIDTH-1:0], val[15:0]);
                        addr = addr + 1;
                    end
                end

                $fclose(fd);

                $display("[INFO] loaded bias file %0s, count=%0d",
                         file_name_i, addr - base_addr_i);
            end
        end
    endtask

    task load_conv_weight_file;
        input [8*384-1:0] file_name_i;
        input integer base_addr_i;
        input integer out_ch_i;
        input integer in_ch_i;
        input integer kernel_i;

        integer oc;
        integer ic;
        integer ky;
        integer kx;
        integer weight_addr;

        begin
            fd = $fopen(file_name_i, "r");

            if (fd == 0) begin
                $display("[WARN] cannot open %0s", file_name_i);
            end
            else begin
                for (oc = 0; oc < out_ch_i; oc = oc + 1) begin
                    for (ic = 0; ic < in_ch_i; ic = ic + 1) begin
                        for (ky = 0; ky < kernel_i; ky = ky + 1) begin
                            for (kx = 0; kx < kernel_i; kx = kx + 1) begin

                                code = 0;

                                while ((code != 1) && !$feof(fd)) begin
                                    code = $fgets(line_r, fd);
                                    if (code != 0) begin
                                        code = $sscanf(line_r, "%h", val);
                                    end
                                end

                                if (code == 1) begin
                                    weight_addr =
                                        base_addr_i +
                                        (((oc * in_ch_i + ic) * kernel_i * kernel_i) +
                                         (ky * kernel_i) +
                                         kx);

                                    axi_write(W_WEIGHT, weight_addr[AXI_WORD_ADDR_WIDTH-1:0], val[15:0]);
                                end
                                else begin
                                    $display("[WARN] unexpected EOF in conv weight file %0s", file_name_i);
                                end

                            end
                        end
                    end
                end

                $fclose(fd);

                $display("[INFO] loaded conv weight file %0s", file_name_i);
            end
        end
    endtask

    task load_fc1_weight_file;
        input [8*384-1:0] file_name_i;
        input integer base_addr_i;
        input integer out_len_i;
        input integer in_len_i;

        integer o;
        integer chunk;
        integer bank;
        integer ii;
        integer block_base;
        integer local_col;
        integer weight_addr;
        integer packed_addr;
        integer chunk_count;
        integer weight_count;
        integer expect_count;
        reg [15:0] fc_weight_mem [0:65535];

        begin
            fd = $fopen(file_name_i, "r");

            if (fd == 0) begin
                $display("[WARN] cannot open %0s", file_name_i);
            end
            else begin
                weight_count = 0;
                while ($fgets(line_r, fd)) begin
                    code = $sscanf(line_r, "%h", val);
                    if (code == 1) begin
                        fc_weight_mem[weight_count] = val[15:0];
                        weight_count = weight_count + 1;
                    end
                end
                $fclose(fd);

                expect_count = out_len_i * in_len_i;
                if (weight_count < expect_count) begin
                    $display("[WARN] fc1 weight file %0s has only %0d values, expected %0d",
                             file_name_i, weight_count, expect_count);
                end
                if ((base_addr_i % NBANKS) != 0) begin
                    $display("[WARN] FC1 weight base %0d is not %0d-bank aligned", base_addr_i, NBANKS);
                end

                chunk_count = (in_len_i + 3) / 4;

                for (o = 0; o < out_len_i; o = o + 1) begin
                    for (chunk = 0; chunk < chunk_count; chunk = chunk + 1) begin
                        packed_addr = (base_addr_i / NBANKS) + (o * chunk_count) + chunk;
                        block_base  = (chunk / 4) * 16;
                        local_col   = chunk % 4;

                        for (bank = 0; bank < 4; bank = bank + 1) begin
                            ii = block_base + (bank * 4) + local_col;
                            weight_addr = (packed_addr * NBANKS) + bank;

                            if ((ii < in_len_i) && (((o * in_len_i) + ii) < weight_count)) begin
                                axi_write(W_WEIGHT, weight_addr[AXI_WORD_ADDR_WIDTH-1:0],
                                          fc_weight_mem[(o * in_len_i) + ii]);
                            end
                            else begin
                                axi_write(W_WEIGHT, weight_addr[AXI_WORD_ADDR_WIDTH-1:0],
                                          {AXI_DATA_DWIDTH{1'b0}});
                            end
                        end

                        weight_addr = (packed_addr * NBANKS) + 4;
                        axi_write(W_WEIGHT, weight_addr[AXI_WORD_ADDR_WIDTH-1:0],
                                  {AXI_DATA_DWIDTH{1'b0}});
                    end
                end

                $display("[INFO] loaded fc1 block16-transposed weight file %0s, count=%0d", file_name_i, weight_count);
            end
        end
    endtask

    task load_fc_linear_weight_file;
        input [8*384-1:0] file_name_i;
        input integer base_addr_i;
        input integer out_len_i;
        input integer in_len_i;

        integer o;
        integer chunk;
        integer bank;
        integer ii;
        integer weight_addr;
        integer packed_addr;
        integer chunk_count;
        integer weight_count;
        integer expect_count;
        reg [15:0] fc_weight_mem [0:65535];

        begin
            fd = $fopen(file_name_i, "r");

            if (fd == 0) begin
                $display("[WARN] cannot open %0s", file_name_i);
            end
            else begin
                weight_count = 0;
                while ($fgets(line_r, fd)) begin
                    code = $sscanf(line_r, "%h", val);
                    if (code == 1) begin
                        fc_weight_mem[weight_count] = val[15:0];
                        weight_count = weight_count + 1;
                    end
                end
                $fclose(fd);

                expect_count = out_len_i * in_len_i;
                if (weight_count < expect_count) begin
                    $display("[WARN] fc linear weight file %0s has only %0d values, expected %0d",
                             file_name_i, weight_count, expect_count);
                end
                if ((base_addr_i % NBANKS) != 0) begin
                    $display("[WARN] FC linear weight base %0d is not %0d-bank aligned", base_addr_i, NBANKS);
                end

                chunk_count = (in_len_i + 3) / 4;

                for (o = 0; o < out_len_i; o = o + 1) begin
                    for (chunk = 0; chunk < chunk_count; chunk = chunk + 1) begin
                        packed_addr = (base_addr_i / NBANKS) + (o * chunk_count) + chunk;

                        for (bank = 0; bank < 4; bank = bank + 1) begin
                            ii = (chunk * 4) + bank;
                            weight_addr = (packed_addr * NBANKS) + bank;

                            if ((ii < in_len_i) && (((o * in_len_i) + ii) < weight_count)) begin
                                axi_write(W_WEIGHT, weight_addr[AXI_WORD_ADDR_WIDTH-1:0],
                                          fc_weight_mem[(o * in_len_i) + ii]);
                            end
                            else begin
                                axi_write(W_WEIGHT, weight_addr[AXI_WORD_ADDR_WIDTH-1:0],
                                          {AXI_DATA_DWIDTH{1'b0}});
                            end
                        end

                        weight_addr = (packed_addr * NBANKS) + 4;
                        axi_write(W_WEIGHT, weight_addr[AXI_WORD_ADDR_WIDTH-1:0],
                                  {AXI_DATA_DWIDTH{1'b0}});
                    end
                end

                $display("[INFO] loaded fc linear weight file %0s, count=%0d", file_name_i, weight_count);
            end
        end
    endtask

    task load_input_file_to_ping;
        input [8*384-1:0] file_name_i;
        input integer height_i;
        input integer width_i;

        integer bank_idx;
        integer row_block_idx;
        integer row_idx;
        integer col_idx;
        integer bank_depth;
        integer axi_addr;
        integer pixel_idx;
        reg [15:0] input_mem [0:783];

        begin
            $readmemh(file_name_i, input_mem);
            bank_depth = ((height_i + NBANKS - 1) / NBANKS) * width_i;

            for (addr = 0; addr < bank_depth; addr = addr + 1) begin
                row_block_idx = addr / width_i;
                col_idx       = addr % width_i;

                for (bank_idx = 0; bank_idx < NBANKS; bank_idx = bank_idx + 1) begin
                    row_idx   = (row_block_idx * NBANKS) + bank_idx;
                    axi_addr  = (addr * NBANKS) + bank_idx;
                    pixel_idx = (row_idx * width_i) + col_idx;

                    if (row_idx < height_i) begin
                        axi_write(W_PING_FM, axi_addr[AXI_WORD_ADDR_WIDTH-1:0], input_mem[pixel_idx]);
                    end
                    else begin
                        axi_write(W_PING_FM, axi_addr[AXI_WORD_ADDR_WIDTH-1:0], {AXI_DATA_DWIDTH{1'b0}});
                    end
                end
            end

            $display("[INFO] loaded row-cyclic IFM from %0s height=%0d width=%0d bank_depth=%0d",
                     file_name_i, height_i, width_i, bank_depth);
        end
    endtask

    initial begin
        RST           = 1'b0;
        axi_waddr_i   = {AXI_ADDR_WIDTH{1'b0}};
        axi_wdata_i   = {AXI_DATA_DWIDTH{1'b0}};
        axi_wvalid_i  = 1'b0;
        axi_raddr_i   = {AXI_ADDR_WIDTH{1'b0}};
        axi_arvalid_i = 1'b0;

        repeat (5) @(posedge CLK);

        @(negedge CLK);
        RST = 1'b1;

        axi_write(W_LOAD_CTRL, 0, 16'd1);

        load_input_file_to_ping(INPUT_Q16_FILE, 28, 28);

        load_bias_file(
            "fixed_q16_params/conv1_bias_q16.txt",
            CONV1_B_BASE
        );

        load_conv_weight_file(
            "fixed_q16_params/conv1_weight_q16.txt",
            CONV1_W_BASE,
            8,
            1,
            5
        );

        load_bias_file(
            "fixed_q16_params/conv2_bias_q16.txt",
            CONV2_B_BASE
        );

        load_conv_weight_file(
            "fixed_q16_params/conv2_weight_q16.txt",
            CONV2_W_BASE,
            20,
            8,
            5
        );

        load_bias_file(
            "fixed_q16_params/fc1_bias_q16.txt",
            FC1_B_BASE
        );

        load_fc1_weight_file(
            "fixed_q16_params/fc1_weight_q16.txt",
            FC1_W_BASE,
            128,
            320
        );

        load_bias_file(
            "fixed_q16_params/fc2_bias_q16.txt",
            FC2_B_BASE
        );

        load_fc_linear_weight_file(
            "fixed_q16_params/fc2_weight_q16.txt",
            FC2_W_BASE,
            84,
            128
        );

        load_bias_file(
            "fixed_q16_params/fc3_bias_q16.txt",
            FC3_B_BASE
        );

        load_fc_linear_weight_file(
            "fixed_q16_params/fc3_weight_q16.txt",
            FC3_W_BASE,
            10,
            84
        );

        axi_write(W_START, 0, 16'd1);

        for (i = 0; i < 300000; i = i + 1) begin
            axi_read(R_STATUS, 0);

            if (axi_rdata_o[0]) begin
                $display("[INFO] CNN_Core done at cycle-loop %0d", i);
                i = 300000;
            end
        end

        if (!axi_rdata_o[0]) begin
            $display("[FAIL] timeout waiting for done");
        end
        else begin
            $display("[PASS] core completed");
            $display("[RESULT] predict_valid_o = %b, predict_value_o = %d", predict_valid_o, predict_value_o);
        end

        axi_write(W_DONE_CLR, 0, 16'd1);

        #50;
        $finish;
    end

endmodule
